CREATE OR REPLACE FUNCTION CONTAR_EMPLEADOS (DEPARTMENTO NUMBER)
RETURN NUMBER
RESULT_CACHE RELIES_ON (EMPLOYEES)
IS
    NUM_EMPLE NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM_EMPLE FROM EMPLOYEES WHERE DEPARTMENT_ID=DEPARTMENTO;
    RETURN NUM_EMPLE;
END;
/

SELECT DEPARTMENT_NAME,CONTAR_EMPLEADOS(DEPARTMENT_ID) FROM DEPARTMENTS WHERE DEPARTMENT_ID> 5;