CREATE OR REPLACE PROCEDURE PROC1
IS
    V NUMBER:=0;
BEGIN
    DBMS_OUTPUT.PUT_LINE(V);
    SELECT COUNT(*) INTO V FROM EMPLOYEES;
    DBMS_OUTPUT.PUT_LINE(V);
END;
/



SELECT * FROM USER_PLSQL_OBJECT_SETTINGS WHERE NAME='PROC1';

ALTER PROCEDURE PROC1 COMPILE;
ALTER PROCEDURE PROC1 COMPILE DEBUG;

EXECUTE DBMS_TRACE.SET_PLSQL_TRACE(DBMS_TRACE.TRACE_ENABLED_SQL+DBMS_TRACE.TRACE_ALL_CALLS);

EXECUTE PROC1;

EXECUTE DBMS_TRACE.CLEAR_PLSQL_TRACE;