 ALTER SESSION SET PLSQL_CODE_TYPE='NATIVE';
 /
 
 CREATE OR REPLACE PROCEDURE EJEMPLO AS 
 BEGIN
    DBMS_OUTPUT.PUT_LINE('EJEMPLO');
END;
/
 
 
 SELECT * FROM USER_PLSQL_OBJECT_SETTINGS WHERE NAME LIKE 'EJEMPLO';
