CREATE OR REPLACE PACKAGE SOBRECARGA AS 
	FUNCTION CONCATENAR(A NUMBER,B NUMBER) RETURN NUMBER;
	FUNCTION CONCATENAR(A VARCHAR2,B VARCHAR2) RETURN VARCHAR2;
	FUNCTION CONCATENAR(A DATE,B NUMBER) RETURN DATE;
END SOBRECARGA;
/

CREATE OR REPLACE PACKAGE BODY SOBRECARGA AS 
	FUNCTION CONCATENAR(A NUMBER, B NUMBER)
	RETURN NUMBER IS BEGIN
	RETURN A + B;
END CONCATENAR; 

FUNCTION CONCATENAR(A VARCHAR2, B VARCHAR2)
RETURN VARCHAR2 IS BEGIN
RETURN A || ' ' || B;

END;

FUNCTION CONCATENAR(A DATE, B NUMBER)
RETURN DATE IS BEGIN
RETURN A + B;

END;

END SOBRECARGA;
/

SET SERVEROUTPUT ON
EXECUTE DBMS_OUTPUT.PUT_LINE(SOBRECARGA.CONCATENAR('ALBERTO', 'PÈREZ'));

EXECUTE DBMS_OUTPUT.PUT_LINE(SOBRECARGA.CONCATENAR(10,30));

EXECUTE DBMS_OUTPUT.PUT_LINE(SOBRECARGA.CONCATENAR(SYSDATE,10));