CREATE OR REPLACE PROCEDURE CREAR_TABLA (NOMBRE_TABLA VARCHAR2, COLUMNAS VARCHAR2)
AUTHID CURRENT_USER
IS
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE ' || NOMBRE_TABLA || '('||COLUMNAS||')';
END;
/

BEGIN
    CREAR_TABLA('PRU1','CODIGO NUMBER, DATOS VARCHAR2(100)');
END;
/