--EXECUTE IMMEDIATE cadena
INSERT INTO PRU1 VALUES (1,'DATO1');
INSERT INTO PRU1 VALUES (2,'DATO2');
INSERT INTO PRU1 VALUES (3,'DATO3');


   
CREATE OR REPLACE function EJEMPLO_DML (CONDICION VARCHAR2)
RETURN NUMBER
AUTHID CURRENT_USER --DEFINER
IS
   COMANDO VARCHAR2(100);
   FILAS NUMBER;
BEGIN
   COMANDO:='DELETE FROM PRU1 WHERE '|| CONDICION;
   DBMS_OUTPUT.PUT_LINE(COMANDO);
   EXECUTE IMMEDIATE COMANDO;
   FILAS:=SQL%ROWCOUNT;
   RETURN FILAS;
END;
/

DECLARE
    CONDICION VARCHAR2(100);
    NUM_FILAS NUMBER;
BEGIN
    CONDICION := 'CODIGO=1';
    NUM_FILAS := EJEMPLO_DML(CONDICION);
    
    DBMS_OUTPUT.PUT_LINE('SE HAN BORRADO ' || NUM_FILAS ||' FILAS');
END;
