CREATE OR REPLACE FUNCTION NUM_EMPLE(DEPARTAMENTO NUMBER)
RETURN NUMBER
IS  
    COMANDO VARCHAR2(200);
    NUM_EMPLEADOS NUMBER;
BEGIN
    COMANDO:='SELECT COUNT(*) FROM EMPLOYEES WHERE DEPARTMENT_ID=:DEPARTAMENTO';
    EXECUTE IMMEDIATE COMANDO INTO NUM_EMPLEADOS USING DEPARTAMENTO;
    RETURN NUM_EMPLEADOS;
END;
/
    
DECLARE
    DEPART NUMBER;
    EMPLE NUMBER;
BEGIN
    DEPART:=100;
    EMPLE:=NUM_EMPLE(DEPART);
    DBMS_OUTPUT.PUT_LINE('HAY '||EMPLE ||' EMPLEADOS EN EL DEPARTAMENTO '|| DEPART);
END;
/