DECLARE 
  -- CREAR UN TIPO
  TYPE EMPLE_TYPE IS RECORD
  (
    NOMBRE_COMPLETO VARCHAR2(100),
    SALARIO NUMBER,
    IMPUESTOS NUMBER
    );
    
  -- CREAR TABLE INDEX TABLE 
  TYPE EMPLEADO IS TABLE OF EMPLE_TYPE INDEX BY PLS_INTEGER;
  
  EMPLEADOS EMPLEADO;
  CONDICION NUMBER;
  COMANDO VARCHAR2(1000);
  
  --CREAMOS UN REF CURSOR
  TYPE V_CURSOR IS REF CURSOR;
  C1 V_CURSOR;
  
BEGIN
    CONDICION:=5000;
    COMANDO:='SELECT FIRST_NAME '||' '||' LAST_NAME,SALARY, SALARY*15/100 FROM EMPLOYEES WHERE SALARY > :CONDICION ORDER BY SALARY DESC';
    OPEN C1 FOR COMANDO USING CONDICION;
    FETCH C1 BULK COLLECT INTO EMPLEADOS ;
    
    FOR X IN 1..EMPLEADOS.COUNT()
    LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLEADOS(X).NOMBRE_COMPLETO||' '||EMPLEADOS(X).SALARIO||' '||EMPLEADOS(X).IMPUESTOS);
    END LOOP;
END;
/