CREATE OR REPLACE FUNCTION BUSCAR_EMPLEADO(CODIGO NUMBER)
RETURN VARCHAR2
IS
    ID_CURSOR INTEGER;
    NUM_FILAS INTEGER;
    NOMBRE VARCHAR2(100);
BEGIN

    ID_CURSOR:=DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(ID_CURSOR, 'SELECT FIRST_NAME,SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID= :COD', DBMS_SQL.NATIVE);
    DBMS_SQL.DEFINE_COLUMN(ID_CURSOR, 1, NOMBRE, 20);
    
    DBMS_SQL.BIND_VARIABLE(ID_CURSOR,':COD',CODIGO);
    
    NUM_FILAS:=DBMS_SQL.EXECUTE(ID_CURSOR);
    IF DBMS_SQL.FETCH_ROWS(ID_CURSOR) = 0 THEN
        RETURN 'NO EXISTE EL EMPLEADO';
    END IF;
    DBMS_SQL.COLUMN_VALUE(ID_CURSOR, 1, NOMBRE);
    DBMS_SQL.CLOSE_CURSOR(ID_CURSOR);
    RETURN NOMBRE;
END;
/


SET SERVEROUTPUT ON
BEGIN
   DBMS_OUTPUT.PUT_LINE(BUSCAR_EMPLEADO(0));
END;