CREATE OR REPLACE PACKAGE PAQ1
AS
  TYPE C_VARIABLE IS REF CURSOR;
  FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE ,X NUMBER) RETURN VARCHAR2;
END;
/

CREATE OR REPLACE PACKAGE BODY PAQ1 AS
   FUNCTION DEVOLVER_DATOS(C1 IN OUT C_VARIABLE ,X NUMBER) RETURN VARCHAR2
   IS     
        empleados_array EMPLEADOS%ROWTYPE;
        notas_array NOTAS%ROWTYPE;
   BEGIN
        IF X=1 THEN
            OPEN C1 FOR SELECT *  FROM EMPLEADOS;
            FETCH C1 INTO empleados_array;
            RETURN empleados_array.nombre; 
            
        ELSE
            OPEN C1 FOR SELECT *  FROM NOTAS;
            FETCH C1 INTO notas_array;
            RETURN notas_array.nombre; 
        END IF;
    END;
END;
/

SET SERVEROUT ON;
DECLARE
    DATOS PAQ1.C_VARIABLE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(PAQ1.DEVOLVER_DATOS(DATOS,1));
    DBMS_OUTPUT.PUT_LINE(PAQ1.DEVOLVER_DATOS(DATOS,2));
END;
/
