CREATE TABLE CONTROL_LOG
(
    EVENTO VARCHAR2(100),
    FECHA DATE DEFAULT SYSDATE
);
/

CREATE OR REPLACE TRIGGER BORRAR_OBJETO
AFTER DROP 
ON SCHEMA
BEGIN
    INSERT INTO CONTROL_LOG (EVENTO) VALUES ('HEMOS BORRADO UN OBJETO '||ora_database_name);
END;
/

CREATE TABLE P1 (CODIGO NUMBER);

DROP TABLE P1;

SELECT * FROM CONTROL_LOG;