CREATE OR REPLACE TRIGGER BORRAR_OBJETO
AFTER DROP 
ON SCHEMA
BEGIN
    INSERT INTO CONTROL_LOG (EVENTO) VALUES ('HEMOS BORRADO UN OBJETO LLAMADO '||ORA_DICT_OBJ_NAME||' DE TIPO '||ORA_DICT_OBJ_TYPE||' QUE PERTENECE AL USUARIO:'||ORA_DICT_OBJ_OWNER);
END;
/
CREATE TABLE P1 (CODIGO NUMBER);

DROP TABLE P1;

SELECT * FROM CONTROL_LOG;