CREATE OR REPLACE TRIGGER BORRAR_OBJETO
AFTER DROP 
ON DATABASE
BEGIN
    INSERT INTO CURSO.CONTROL_LOG (EVENTO) VALUES ('HEMOS BORRADO UN OBJETO A NIVEL DE DATABASE LLAMADO '||ORA_DICT_OBJ_NAME||' DE TIPO '||ORA_DICT_OBJ_TYPE||' QUE PERTENECE AL USUARIO:'||ORA_DICT_OBJ_OWNER);
END;
/