CREATE TABLE CLIENTES
(
CODIGO NUMBER,
NOMBRE VARCHAR2(100),
FOTO BFILE,
LONGITUD NUMBER);

/

INSERT INTO CLIENTES VALUES ( 1,'ROSA',NULL,NULL);

INSERT INTO CLIENTES VALUES (2,'PEDRO',NULL,NULL); 

INSERT INTO CLIENTES VALUES ( 3,'ANTONIO',NULL,NULL); 

INSERT INTO CLIENTES VALUES ( 4,'RAUL',NULL,NULL); 

INSERT INTO CLIENTES VALUES ( 5,'MARIA',NULL,NULL);

/


SELECT * FROM CLIENTES;