CREATE OR REPLACE FUNCTION TAM (DIRECTORIO VARCHAR2, CODIGO NUMBER)
RETURN NUMBER
IS
    FICHERO VARCHAR2(100);
    FOTO BFILE;
BEGIN
    FICHERO:='cliente'||CODIGO||'.jpg';
    FOTO:=BFILENAME(DIRECTORIO,FICHERO);
    IF DBMS_LOB.FILEEXISTS(FOTO)=1 THEN
        RETURN DBMS_LOB.GETLENGTH(FOTO);
    ELSE
        RETURN 0;
    END IF;
END;
/

SET SERVEROUTPUT ON
EXECUTE DBMS_OUTPUT.PUT_LINE(TAM('FICHEROS',1));