CREATE OR REPLACE PROCEDURE CARGA_CLIENTES 
IS 
    CURSOR CLI IS SELECT * FROM CLIENTES FOR UPDATE; 
    FICHERO VARCHAR2(100) ; 
BEGIN 
    FOR CLI IN CLI LOOP 
        FICHERO:='cliente'||CLI.CODIGO||'.jpg'; 
        DBMS_LOB.CREATEFILE(FICHERO,'FICHEROS'); 
        DBMS_LOB.WRITEAPPEND(FICHERO,CLI.FOTO); 
    END LOOP;
END;
/