CREATE OR REPLACE PROCEDURE CARGA_CLIENTES IS CURSOR 
CLI IS SELECT * FROM CLIENTES FOR UPDATE; FICHERO 
VARCHAR2(100) ; 
BEGIN 
	FOR C1 IN CLI LOOP FICHERO := '||CLI.CODIGO||';
	UPDATE CLIENTES
	SET
	    FOTO = BFILENAME(
	        ',FICHERO),LONGITUD = TAM(',
	        C1.CODIGO
	    )
	WHERE CURRENT OF CLI;
	E 
END LOOP; 

END;

/

EXECUTE CARGA_CLIENTES;