ALTER TABLE CLIENTES ADD DESCRIPCION CLOB;
/
DESC CLIENTES;
/
SELECT * FROM CLIENTES;
/
DECLARE
    TEXTO VARCHAR2(50):='DESCRIPCION DEL CLIENTE:';
BEGIN
    FOR X IN 1..5 LOOP
        UPDATE  CLIENTES SET DESCRIPCION=TEXTO||X WHERE CODIGO=X;
    END LOOP;
END;
/

CREATE TABLE PRUEBA_LOB (DESCRI CLOB);

DESC PRUEBA_LOB;

CREATE OR REPLACE PROCEDURE CARGA_DESCRI
IS
    CURSOR CLI IS SELECT * FROM CLIENTES FOR UPDATE;
    TEMPORAL CLOB; 
    CANTIDAD INTEGER:=5;
    POSICION INTEGER:=1;
BEGIN
    FOR C1 IN CLI LOOP 
        --ABRIR EL FICHERO. ES OBLIGATORIO 
        DBMS_LOB.OPEN(C1.DESCRIPCION,DBMS_LOB.LOB_READONLY);
        
       --LEEMOS 5 POSICIONES DE NUESTRO CAMPO DESCRIPCION Y LO DEJAMOS EN LA VARIABLE TEMPORAL
        DBMS_LOB.READ(C1.DESCRIPCION,CANTIDAD,POSICION,TEMPORAL);
        
        INSERT INTO PRUEBA_LOB VALUES(TEMPORAL);
        
       --CERRAR EL LOB
        DBMS_LOB.CLOSE(C1.DESCRIPCION);
    END LOOP;
END;
/

EXECUTE CARGA_DESCRI;

SELECT * FROM PRUEBA_LOB;

SELECT * FROM CLIENTES;