CREATE TABLE PRUEBA_LOB1 (EMPLEADO CLOB);
/

CREATE OR REPLACE PROCEDURE CARGA_EMPLE
IS
    CURSOR CLI IS SELECT * FROM EMPLOYEES;
    TEMPORAL CLOB; 
    CANTIDAD INTEGER;
    NOMBRE VARCHAR2(100);
BEGIN
    FOR C1 IN CLI LOOP 
        
        --ES NECESARIO CREAR UN LOB TEMPORAL, PARA INICIALIZAR EL LOCALIZADOR
        DBMS_LOB.CREATETEMPORARY(TEMPORAL,TRUE);
        
        --ABRIR EL LOB, EN MODO ESCCRITURA
        DBMS_LOB.OPEN(TEMPORAL,  DBMS_LOB.LOB_READWRITE);    
           
       --VARIABLE FORMADA POR EL NOMBRE Y APELLIDO DEL EMPLEADO
        NOMBRE:=C1.FIRST_NAME||' '|| C1.LAST_NAME;
        
        --VARIALBE CON LA LONGITUD DLE NOMBRE
        CANTIDAD:=LENGTH(NOMBRE);
        
        --ESCRIBIMOS EN LA VARIABLE LOB LOS DATOS
        DBMS_LOB.WRITE(TEMPORAL,CANTIDAD,1,NOMBRE);
        
       -- INSERTAMOS EN LA TABLA
        INSERT INTO PRUEBA_LOB1 VALUES(TEMPORAL);
        
        --CERRAMOS EL FICHEROS       
        DBMS_LOB.CLOSE(TEMPORAL);
    END LOOP;
END;
/

EXECUTE CARGA_EMPLE;

SELECT * FROM PRUEBA_LOB1;