SELECT * FROM CLIENTES;

SELECT DESCRIPCION, DBMS_LOB.SUBSTR(DESCRIPCION,10,1) AS TEXTO FROM CLIENTES;

SELECT DESCRIPCION, DBMS_LOB.INSTR(DESCRIPCION,'1') FROM CLIENTES;

SELECT DBMS_LOB.SUBSTR(FOTO,10,1) AS TEXTO FROM CLIENTES;