SET SERVEROUTPUT ON
DECLARE 
  TYPE EMPLEADOS_MAP IS TABLE OF EMPLEADOS%ROWTYPE INDEX BY PLS_INTEGER;

EMPLES EMPLEADOS_MAP ;

BEGIN
    SELECT * BULK COLLECT INTO EMPLES FROM EMPLEADOS;

    FOR I IN 1..EMPLES.COUNT()
    LOOP
        DBMS_OUTPUT.PUT_LINE(EMPLES(I).NOMBRE);
    END LOOP;
END;
/