SET SERVEROUTPUT ON
DECLARE
  TYPE V1 IS VARRAY(50) OF VARCHAR2(100);
  
  VAR1 V1:= V1('ADIOS','HOLA','TERCERO','XXX','ZZZZ');
  
BEGIN
  DBMS_OUTPUT.PUT_LINE(VAR1(1));
  VAR1(1):='HOLA';
  DBMS_OUTPUT.PUT_LINE(VAR1(1));  
  DBMS_OUTPUT.PUT_LINE(VAR1(5));

END;
/