SET SERVEROUTPUT ON
DECLARE
  TYPE V1 IS VARRAY(50) OF VARCHAR2(100);
  
  VAR1 V1:= V1('ADIOS','HOLA','TERCERO','XXX','ZZZZ');
BEGIN
  DBMS_OUTPUT.PUT_LINE('count(): ' || VAR1.COUNT());
  DBMS_OUTPUT.PUT_LINE('limit(): ' || VAR1.LIMIT());

  VAR1.EXTEND();
  DBMS_OUTPUT.PUT_LINE('count(): ' || VAR1.COUNT());

  VAR1.EXTEND(5);
  DBMS_OUTPUT.PUT_LINE('count(): ' || VAR1.COUNT());
END;
/