SET SERVEROUTPUT ON
DECLARE
  TYPE EMPLEADO IS VARRAY(10) OF EMPLOYEES%ROWTYPE;
  
  EMPLEADOS EMPLEADO:=EMPLEADO();
BEGIN
  SELECT * BULK COLLECT INTO EMPLEADOS
  FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;
  FOR I IN EMPLEADOS.FIRST()..EMPLEADOS.LAST() LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME||' '||EMPLEADOS(I).SALARY);
  END LOOP;
END;
/

SET SERVEROUTPUT ON
DECLARE
  TYPE EMPLEADO IS VARRAY(10) OF EMPLOYEES%ROWTYPE;

  CURSOR C1 IS SELECT * 
  FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;

  CONTADOR NUMBER:=1;

  EMPLEADOS EMPLEADO:=EMPLEADO();
BEGIN

  FOR X IN C1 LOOP
    EMPLEADOS.EXTEND(1);
    EMPLEADOS(CONTADOR):=X;
    CONTADOR:=CONTADOR+1;
  END LOOP;
   FOR I IN EMPLEADOS.FIRST..EMPLEADOS.LAST LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME||' '||EMPLEADOS(I).SALARY);
     
  END LOOP;
END;