INSERT INTO PRUEBA VALUES (1, DATO('UNO','DOS'), 'TEXTO');
INSERT INTO PRUEBA VALUES (2, DATO('aa','bb','cc','dd'), 'ejemplo');

SELECT * FROM PRUEBA;
SELECT C2 FROM PRUEBA;

SELECT C1, T2.*, C3 FROM PRUEBA, TABLE(PRUEBA.C2) T2;