SET SERVEROUTPUT ON
DECLARE
  TYPE EMPLEADO IS VARRAY(10) OF EMPLOYEES%ROWTYPE; 
  EMPLEADOS EMPLEADO:=EMPLEADO();
BEGIN
  SELECT * BULK COLLECT INTO EMPLEADOS
  FROM EMPLOYEES FETCH FIRST 10 ROWS ONLY;
  FOR I IN EMPLEADOS.FIRST()..EMPLEADOS.LAST() LOOP
     DBMS_OUTPUT.PUT_LINE(EMPLEADOS(I).FIRST_NAME||' '||EMPLEADOS(I).SALARY);
  END LOOP; 
  DBMS_OUTPUT.PUT_LINE(EMPLEADOS.LAST());
  DBMS_OUTPUT.PUT_LINE(EMPLEADOS.FIRST());
  DBMS_OUTPUT.PUT_LINE(EMPLEADOS.NEXT(1));
  DBMS_OUTPUT.PUT_LINE(EMPLEADOS.NEXT(10));
   IF EMPLEADOS.EXISTS(20) THEN
        DBMS_OUTPUT.PUT_LINE('EXISTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE');
    END IF;
  --EMPLEADOS.DELETE(2);
END;
/