CREATE OR REPLACE TYPE EMPLEADO IS TABLE OF VARCHAR2(100);

CREATE TABLE
    EMPLES (
        CODIGO NUMBER,
        DIRECCION VARCHAR2(100),
        DATOS EMPLEADO
    ) NESTED
TABLE DATOS STORE AS TABLA_DATOS;

/

DESC EMPLES;

SELECT * FROM TAB;