SELECT * FROM USER_DEPENDENCIES;

SELECT * FROM USER_DEPENDENCIES WHERE NAME='EMPLOYEES';

SELECT * FROM USER_DEPENDENCIES WHERE NAME='EMP_DETAILS_VIEW';

SELECT * FROM USER_DEPENDENCIES WHERE NAME='LISTAR';

SELECT * FROM USER_DEPENDENCIES WHERE REFERENCED_NAME='EMPLOYEES';