--DBMS_UTILITY
SET SERVEROUT ON;
EXECUTE dbms_utility.get_dependency('TABLE','CURSO','PRUEBA');
EXECUTE dbms_utility.validate('CURSO','PRUEBA', 1);

/*
1 = TABLE/PROCEDURE/TYPE
2 = BODY
3 = TRIGGER
4 = INDEX
5 = CLUSTER
8 = LOB
9 = DIRECTORY
10 = QUEUE
*/

EXECUTE DBMS_UTILITY.COMPILE_SCHEMA('CURSO',COMPILE_ALL=>FALSE,REUSE_SETTINGS=>TRUE);